### ISSUE TITLE
Should mapbox-gl-layer allow blocks?

### ISSUE THREAD

**Issue by allthesignals** [kturney/ember-mapbox-gl#110]
When invoked without explicit ID, Source and Layer IDs are private and generated automatically:

```handlebars
<map.source
  @options={{hash
    type='geojson'
    data=this.CONSTANTS.EXISTING_TRAILS_URL
  }} as |source|
>
  <source.layer
    @layer={{this.trailStyle}}
    as |layer|
  />
</map.source>
```

If you want to do anything specific to that layer, such as hover events, `<HoverableLayer />`, clicking, etc, you'll need to manage your own IDs, and this can get unwieldy and ultimately break the experience of composing layers (as visual elements) inside the templates.

It would be helpful to know at least what this id was through a reference somewhere:
```handlebars
<map.source
  @options={{hash
    type='geojson'
    data=this.CONSTANTS.EXISTING_TRAILS_URL
  }} as |source|
>
  <source.layer
    @layer={{this.trailStyle}}
    as |layer|
  />
    <HoverableLayer
      @layer={{layer}}
    />
  </source.layer>
</map.source>
```

Would this make any sense or is there a cleaner way?

**Comment by kturney** [comment]
So mostly you'd like source and layer to yield their IDs? Seems reasonable enough.

**Comment by allthesignals** [comment]
> So mostly you'd like source and layer to yield their IDs? Seems reasonable enough.

Yup! Will PR something just wanted to check with you

**Comment by kturney** [comment]
sounds great!
