### ISSUE TITLE
component options should be named the same as mapbox gl's api

### ISSUE THREAD

**Issue by allthesignals** [kturney/ember-mapbox-gl#2]
This component takes options for this like "paint" but they are called "paintOptions". It'd be more intuitive if these option names matched what they're called in Mapbox GL: https://www.mapbox.com/mapbox-gl-js/example/geojson-polygon/. 

*Update*

Our priorities for this repo are:
> We add the maximum power API so no one is ever blocked in using a feature. However, that doesn't preclude us from adding necities on top that layer on to the power user API. 

We've identified the need to allow these components to accept an opaque `options` object:
 - [x] mapbox-gl-layer (currently `layoutOptions` `paintOptions`) (pr: https://github.com/kturney/ember-mapbox-gl/pull/8)
 - [ ] mapbox-gl (currently `initOptions`)
 - [ ] mapbox-gl-popup (currently `initOptions`)
 - [ ] mapbox-gl-source (currently `sourceId` `data` `sourceId`, see [here](https://github.com/kturney/ember-mapbox-gl/blob/master/addon/components/mapbox-gl-source.js))
 - [ ] mapbox-gl-marker (currently `initOptions`)
 - [ ] mapbox-gl-control (currently `control` `position`, as positionalParams)

 - [ ] mapbox-gl-on
 - [ ] mapbox-gl-call

**Comment by danielthall** [comment]
Any opposition to mapbox-gl-layer taking an opaque `options` object that just passes on? I just did this for mapbox-gl-source, and is fairly straightforward. Should keep us closer to mapbox going forward. I can merge in `paintOptions` and `layoutOptions` if they are passed so we stay backward compatible.

**Comment by allthesignals** [comment]
@danielthall I think that's great, right now I believe the property is called `initOptions`, so an alias would be nice (that was the first thing I tried). Without it, people will have to configure style through `environment.js` which is bit of a non-starter. Can we see a PR? I think it'd help move the needle on this issue. 

In general, however, I'd argue for no general options property but simply allowing passage of specific options themselves, which seems closer to what Mapbox allows: https://www.mapbox.com/mapbox-gl-js/api/#map. 

For example:
```
var map = new mapboxgl.Map({
    container: 'map', // container id
    style: 'mapbox://styles/mapbox/streets-v9', // stylesheet location
    center: [-74.50, 40], // starting position [lng, lat]
    zoom: 9 // starting zoom
});
```
would translate to:
```
{{mapbox-gl container='map' style='mapbox://styles/mapbox/streets-v9' center=latLng zoom=9}}
```

This approach is also in line with the ember-leaflet implementation, which has been successful: http://www.ember-leaflet.com/docs/leaflet-map

Either way, as long it's documented well, it shouldn't matter. I guess it depends on the priorities for this library - do we focus on API design or integrations? @kturney has mentioned his approach has been to make this as a lightweight wrapper in which most users can refer to MapboxGL's documentation instead of looking at how this addon maps behaviors to MapboxGL's.

**Comment by danielthall** [comment]
@allthesignals Yeah, I could go either way. The only reason I like the `options` hash route, is so we can more or less have parity with Mapbox without having to keep up with every attribute they may decide to add.

That said, it makes it harder for us to test that our addon actually _works_. Selfishly, I'd like to propose the options hash as a short term solution (I need to add `filter` to a `layer` for something I'm working on), but long term maybe we consider taking the leaflet approach. I'm working on a PR for just `mapbox-gl-layer` but can maybe get to the other components.

**Comment by kturney** [comment]
So the way I see it. We add the maximum power API so no one is ever blocked in using a feature. However, that doesn't preclude us from adding necities on top that layer on to the power user API. So for now I say @danielthall starts with the power API and we can add the nice API later. What do y'all think?

**Comment by allthesignals** [comment]
> I'm working on a PR for just mapbox-gl-layer but can maybe get to the other components.

I'll make a list for these other layers and revise this issue to be more specific of an ask.

> so we can more or less have parity with Mapbox without having to keep up with every attribute they may decide to add

I won't belabor the point because I think you're right that it should just be `options` (more intuitive + good documentation will take care of it!), but out of curiosity I'm guessing this is because Ember components don't distinguish between properties passed explicitly from outside the component and properties defined internally? 

> We add the maximum power API so no one is ever blocked in using a feature. 

Agree! Allow features, then optimize later.

**Comment by kturney** [comment]
I thinks it's mainly so changes to the mapbox API require minimal changes
to the ember bindings.

**Comment by chriswhong** [comment]
Just hit this now, I want to use `minzoom` but there's no way to do it since `options` that gets passed to `addLayer` only includes: 
```
{
      id: options.id ? options.id : this.layerId,
      type: options.type ? options.type : layerType,
      source: options.source ? options.source : sourceId,
      layout: assign({}, layerConfig.layout, options.layout ? options.layout : layoutOptions),
      paint: assign({}, layerConfig.paint, options.paint ? options.paint : paintOptions),
    }
```

+1 on just allow for creating a layer configuration object the way you would when using `addLayer()` normally, it makes the implementation simpler since you don't split it up at all, just pass it along to `addLayer`.  `addLayer will let you know if you forgot anything.

**Comment by chriswhong** [comment]
Also, it would be nice to make my own layer ids instead of `guid`ing them... not sure if I missed something but want to be able to `queryRenderedFeatures` and need an easy name to call.

**Comment by allthesignals** [comment]
@chriswhong I think layer id is set on the layer component with `id=`.

For `mapbox-gl-layer` options, we could use [assign](https://emberjs.com/api/ember/2.14/namespaces/Ember/methods?anchor=assign), as it's also used in the  [`mapbox-gl` component](https://github.com/kturney/ember-mapbox-gl/blob/master/addon/components/mapbox-gl.js). I think it makes sense to provide defaults, but allow overrides and definition of new properties, especially for top-level object properties (to @chriswhong's point).

**Comment by danielthall** [comment]
Here's a thought-

What if we stick with the opaque object path, but name the properties the same as in the Mapbox api? Example:

`mapbox-gl-source` as of my PR yesterday takes an `options` object, but Mapbox's docs call for an `id` and `source` object. [Mapbox Docs](https://www.mapbox.com/mapbox-gl-js/api/#map#addsource). We could still make `id` optional , and generate one if it's not passed.

**New Usage**

```js
{{map.source id='foo'
    source=(hash
      data=myData
      cluster=true
      clusterRadius=200)}}
```

Similarly, `mapbox-gl-layer` could be changed to follow Mapbox's `layer` object and `before` string. [Mapbox Docs](https://www.mapbox.com/mapbox-gl-js/api/#map#addlayer)

**New Usage**

```js
{{map.layer layer=(hash
    source='foo'
    type='circle'
    paint=(hash
      circle-color='#bada55'
      circle-radius=70
      circle-blur=1
      circle-opacity=0.3)
    )
    before='water'
}}
```

And so on.

Thoughts?

**Comment by allthesignals** [comment]
@danielthall yes, this is the approach I endorse - I like the idea of sticking to the parameter names as they're defined in the documentation. 

My instinct was to have something like this: 
```hbs
{{map.layer
    source='foo'
    type='circle'
    paint=(hash
      circle-color='#bada55'
      circle-radius=70
      circle-blur=1
      circle-opacity=0.3)
    before='water'
}}
```

But that doesn't make sense because the documentation specifies only 2 arguments for addLayer :) this would awkwardly flatten the layer object parameter with the other allowed parameters.

So, let's stick strictly to the naming convention here, and I think that's great:
![image](https://user-images.githubusercontent.com/5004319/29007285-744280d8-7acd-11e7-9c4e-077e131f8325.png)

**Comment by danielthall** [comment]
I can likely work on these this week. How do we feel about `initOptions` vs `options`? cc: @kturney

**Comment by danielthall** [comment]
Started a `mapbox-api-unification` branch for all of this work. I'd like to get it all in one big PR, so I'll be commiting to that branch. 

Anyone want to take a look at the [first commit](https://github.com/kturney/ember-mapbox-gl/commit/b3b4abb76cd8865da20c780c700da0169a50c898)? Comments, edits and suggestions welcome

**Comment by allthesignals** [comment]
@danielthall fantastic - I can take a look tomorrow. Happy to see this effort coming together.

Would also appreciate review of my PR here: https://github.com/kturney/ember-mapbox-gl/pull/11. cc @kturney, though it may become redundant with changes made inside `mapbox-api-unification`.

Thanks, folks!

**Comment by danielthall** [comment]
@allthesignals I think it will be accomplished with `mapbox-api-unification`. I'm happy to get your PR merged in the meantime if it is critical for your project.

I did miss adding the `id` property, but can get that in to my branch.

**Comment by allthesignals** [comment]
Can we check some of these off?
