### ISSUE TITLE
Add documentation with ember-cli-addon-docs

### ISSUE THREAD

**Issue by allthesignals** [kturney/ember-mapbox-gl#4]
See here: https://ember-learn.github.io/ember-cli-addon-docs/#/. 

I would also love to see a step-by-step getting started guide similar to ember-leaflet: http://www.ember-leaflet.com/docs. Having plenty of examples will help onboard people more. 

 - [ ] Documentation site
 - [x] Improved README

**Comment by ynotdraw** [comment]
I'd be happy to lend a hand with this

**Comment by allthesignals** [comment]
@ynotdraw would love that, especially a slick design for it... I can help with implementation. Should this just be the dummy app in tests? Move the build of it up into a `gh-pages` branch?

**Comment by ynotdraw** [comment]
@allthesignals sounds like a great plan to me! 👍

**Comment by patodevilla** [comment]
Does anyone have an example of how to use this addon?

**Comment by kturney** [comment]
hi @patodevilla,

There is a very minimal example in [the dummy app](https://github.com/kturney/ember-mapbox-gl/tree/master/tests/dummy), and I have been slowly working on docs in [the docs branch](https://github.com/kturney/ember-mapbox-gl/tree/docs/docs).

**Comment by patodevilla** [comment]
Thank you very much @kturney!

**Comment by allthesignals** [comment]
Also heard good things about ember-addon-docs

**Comment by allthesignals** [comment]
@kturney what is the docs branch you're referring to? I'm starting a new branch using this addon.

**Comment by ynotdraw** [comment]
@allthesignals I actually worked with @kturney on updating the branch and getting it merged in.  It's currently here: https://github.com/kturney/ember-mapbox-gl/blob/master/API.md

**Comment by allthesignals** [comment]
@ynotdraw sweet! I'm installing the [addon docs addon](https://ember-learn.github.io/ember-cli-addon-docs/latest/docs/quickstart), and I can start moving your documentation over to it... I'll follow the same page organization. Is that cool?

**Comment by ynotdraw** [comment]
@allthesignals totally!  That sounds great. Feel free to move things around as they make sense as well!

**Comment by allthesignals** [comment]
Started a [branch](https://github.com/allthesignals/ember-mapbox-gl/tree/4-documentation), dealing with [some](https://github.com/ember-learn/ember-cli-addon-docs/issues/136#issuecomment-381299313) [issues](https://github.com/ember-learn/ember-cli-addon-docs/issues/149) so it's not working. Waiting for some replies before I can move ahead.

**Comment by allthesignals** [comment]
Hi! What would you like to see for this to work? I don't know if I have enough permissions to this repository to _deploy_ something to Github pages. I could perhaps PR something to `gh-pages` branch, but built-in deployer is opinionated enough that it wants collaborator access.

**Comment by kturney** [comment]
could we make sure we are on latest addon-docs?
I can try to do a deploy this weekend.

**Comment by allthesignals** [comment]
Will do - thanks @kturney!

**Comment by kturney** [comment]
finally published! https://kturney.github.io/ember-mapbox-gl
