### ISSUE TITLE
Cannot read property 'removeSource' of undefined

### ISSUE THREAD

**Issue by patodevilla** [kturney/ember-mapbox-gl#42]
Anyone else getting this error? I upgraded the version to the current one and started having problems
<img width="1280" alt="screen shot 2018-03-17 at 11 15 34 pm" src="https://user-images.githubusercontent.com/13631576/37562912-380d3c2c-2a39-11e8-89dc-bd47f94f955b.png">

I get this error every time a change to a new route after loading the map. If the maps does not have any layers, it works.

I would really appreciate any pointers

"mapbox-gl": "^0.44.0"
"ember-mapbox-gl": "^0.9",
"ember-mapbox-gl-draw": "^1.1.0",

**Comment by kturney** [comment]
Hi @patodevilla,

Does changing https://github.com/kturney/ember-mapbox-gl/blob/75cffa9ac0fb76bc2a1c5874c6b045d20885a20e/addon/components/mapbox-gl-source.js#L57 to `scheduleOnce('afterRender', this.map, this.map.removeSource, sourceId)` fix the issue for you?

I suspect you're hitting a race condition in which the map has been removed before the we attempt to clean up the removed source. The change from `next` to `scheduleOnce` should fix the race condition, if that is indeed what is happening.

I'll also try to get a test for it.

**Comment by kturney** [comment]
I've published the fix for this in 0.9.1.

Thanks for filing the issue!
