### ISSUE TITLE
Geolocation control remove 

### ISSUE THREAD

**Issue by patodevilla** [kturney/ember-mapbox-gl#46]
<img width="1280" alt="screen shot 2018-04-14 at 2 38 39 pm" src="https://user-images.githubusercontent.com/13631576/38771932-97e0fb3e-3ff1-11e8-9958-8fb2231be096.png">

I am getting an error when changing route when using the Geolocation control and the user has denied access to location. Is there a way arround this?

This is how I set up the control

`    this.set('geolocationControl',
      new MapboxGl.GeolocateControl({
        positionOptions: {
            enableHighAccuracy: true
        },
        trackUserLocation: true
      })
    );`

And i simply add it like this
`{{map.control geolocationControl 'top-right'}}`

I would really appreciate any guidelines to solve this.

**Comment by kturney** [comment]
Hi @patodevilla,

I wonder if this isn't a bug in mapbox-gl-js itself.
Assuming that the undefined thing is this._userLocationDotMarker at https://github.com/mapbox/mapbox-gl-js/blob/9090d101e6b6d3f06b9a9e49d54dca4c22bcae74/src/ui/control/geolocate_control.js#L132 and then it was never assigned at https://github.com/mapbox/mapbox-gl-js/blob/9090d101e6b6d3f06b9a9e49d54dca4c22bcae74/src/ui/control/geolocate_control.js#L278

What do you think?
