### ISSUE TITLE
Make `accessToken` optional

### ISSUE THREAD

**Issue by allthesignals** [kturney/ember-mapbox-gl#59]
Right now, we require `accessToken` in the environment for this addon to work, but it's possible to host your own open base styles. Happy to PR this but can you see any issues with this?

**Comment by kturney** [comment]
seems fine. I think mapbox will error on its own if it needs an accessToken and doesn't have one.

**Comment by allthesignals** [comment]
Great. I can just have it warn instead which are [stripped](https://emberjs.com/api/ember/release/modules/@ember%2Fdebug) from production builds. 

It also requires a general config object:

`assert('mapbox-gl config is required in config/environment', mbglConfig);`

I worry this might create confusion especially when instantiating multiple maps. It should be considered a global configuration (but that's probably obvious).

**Comment by kturney** [comment]
I spose we could only show the warning for the first mapbox-gl component rendered.
Maybe a future enhancement.
