### ISSUE TITLE
Fastboot friendliness

### ISSUE THREAD

**Issue by allthesignals** [kturney/ember-mapbox-gl#63]
I've started working with Fastboot and would like to make `ember-mapbox-gl` "turn off" its import of `mapbox-gl` during Fastboot mode. There are a few approaches to this:

1) Conditionally import mapbox-gl using `app.import` and make it globally available - this is how `ember-leaflet` works. Here is a working example: https://github.com/allthesignals/ember-mapbox-gl/tree/fastboot-compatible. 

2) Since we already have ember-auto-import, we can lazy load the dependency (see this issue: https://github.com/ef4/ember-auto-import/issues/98). This would mean refactoring the addon in 4 places to call MapboxGL class methods from a component instance method. 

With this out of the way, fastboot is trivial to enable. 

What are your thoughts?

**Comment by kturney** [comment]
seems like as good a reason as any to actually implement lazy auto loading.

**Comment by danieledraganti** [comment]
Hello everyone, any news about this? I am trying to implement a lazy-loading in-repo engine with this addon, and I am facing more or less of the same problem. I would need to include mapbox-gl in my host app but the point of the engine is exactly not having to do this...
Lazily loading the libraries would be excellent.

**Comment by allthesignals** [comment]
Hi @danidr! I have a branch linked above - I haven't looked at it in a while. It might take quite a bit of work to refactor, but I'm not sure. 

Feel free to take a stab. I don't actually use a lot of fastboot in my work so I probably won't get aroudn to doing it. 

FWIW, I prefer option 2 - I don't like the idea of having something globally available. It might screw up automated testing.

**Comment by danieledraganti** [comment]
Hello @allthesignals, and thank you!
This is not a very Ember-y way, so I agree entirely about option 2 – I'll see what I can manage to do with the global library anyway.
Cheers!

**Comment by kturney** [comment]
published as 0.13.0
