### ISSUE TITLE
Support dependency injection

### ISSUE THREAD

**Issue by allthesignals** [kturney/ember-mapbox-gl#66]
The dependency injection pattern makes integration testing a lot easier because test writers can mock certain "difficult" dependencies and inject them into the subject component. 

Currently, it's not fully possible to inject a mapbox-gl map instance into the mapbox-gl component. While this is fully supported in its other yielded components, it may be necessary for addon consumers to spin up a wrapping mapbox-gl component for their own needs:

```javascript
hbs`
	{{#mapbox-gl map=mockedMapInstance as |map|}}
		{{addon-consumer-component map=map}}
	{{/mapbox-gl}}
`
```

A few things need to happen:

1. In [mapbox-gl component](https://github.com/kturney/ember-mapbox-gl/blob/master/addon/components/mapbox-gl.js#L55), we set `map` to `null`. We could check that map isn't being passed as an arg first.

2. In [_setup](https://github.com/kturney/ember-mapbox-gl/blob/master/addon/components/mapbox-gl.js#L88), we call the private _onLoad hook, which overwrites whatever `map` is currently. 

3. Also, in [_setup](https://github.com/kturney/ember-mapbox-gl/blob/master/addon/components/mapbox-gl.js#L88), we will need a way to still fire the `mapLoaded` hook in case the addon consumer has some important logic there.

Thoughts on this? I'm happy to work on it - all of our projects use maps and it'd be way easier to setup map instances in our tests.

**Comment by kturney** [comment]
how would we set the component's element as the map's container in the case of an injected map?

**Comment by allthesignals** [comment]
Actually, we could just pass a preset object:

```
MapboxGl.Map.bind(null, {
	// whatever overrides here
});
```

Then, `mapbox-gl` can just instantiate it with `new` like normal, except it'll use the passed dependency here:
https://github.com/kturney/ember-mapbox-gl/blob/master/addon/components/mapbox-gl.js#L87

The component would set the container like normal.

This worked pretty nicely for us with Draw:
https://github.com/NYCPlanning/labs-applicantmaps/blob/develop/app/components/project-geometries/modes/draw.js#L9-L15

Alternatively, one thing that has worked if handling async is the only problem is stubbing in a waiter registration: 
```javascript
    this.owner.register('component:labs-map', LabsMap.extend({
      init(...args) {
        this._super(...args);

        if (config.environment === 'test') {
          registerWaiter(() => this.map);
        }
      },
    }));
```
