### ISSUE TITLE
update marker position

### ISSUE THREAD

**Issue by reticulan** [kturney/ember-mapbox-gl#69]
I'm newbee and maybe this question is super easy, but I don't understand this. How I can change marker data from component? I do it through set(), coordinates of marker changes, but marker itself doesn't change position on the map.

**Comment by kturney** [comment]
You can bind the coordinates to the `lngLat` property of the marker component.

https://github.com/kturney/ember-mapbox-gl/blob/master/addon/components/mapbox-gl-marker.js#L20

**Comment by reticulan** [comment]
@kturney thanks a lot!
