### ISSUE TITLE
Add popup to marker

### ISSUE THREAD

**Issue by reticulan** [kturney/ember-mapbox-gl#70]
Hello! I see several ways of adding popup:
1) Version of popup from your popup example: 
```
{{#map.popup lngLat=(array -96.7969879 32.7766642)}}
    Dallas, TX
  {{/map.popup}}
```
this version raises "array is not a helper".
2) Instead of lngLat set marker.  I have valid geojson markers, they displayd on the map, but popup not worked, this version raises "setPopup is not a function" here: 
https://github.com/kturney/ember-mapbox-gl/blob/e10e296b7cb10136a9641694cb01cb36caae7c5e/addon/components/mapbox-gl-popup.js#L75
3) I can set latLng in my component and this works, but I don't like this because I already have markers in my template and pass them through service.

If it's possible, how I can set markers directly  to popup tag?

**Comment by kturney** [comment]
If you would like to use the array helper, there are a few places to get it.
1. It is built in as of [Ember 3.7](https://www.emberjs.com/api/ember/3.7/classes/Ember.Templates.helpers/methods/array?anchor=array)
2. The very nice [ember-composable-helpers](https://github.com/DockYard/ember-composable-helpers#array)
3. A [stand alone add-on](https://github.com/kellyselden/ember-array-helper)
4. Or it is [fairly simple to create yourself](https://github.com/kellyselden/ember-array-helper/blob/master/addon/helpers/array.js#L4)

The marker that the popup expects is an [instance of the Mapbox-gl-marker component](https://github.com/kturney/ember-mapbox-gl/blob/master/addon/components/mapbox-gl-marker.js).

To create a popup with a GeoJSON point, one could do:
```hbs
{{#map.popup lngLat=geojson.coordinates}}
  Dallas, TX
{{/map.popup}}
```

For a GeoJSON feature with a point:
```hbs
{{#map.popup lngLat=feature.geometry.coordinates}}
  Dallas, TX
{{/map.popup}}
```

Hope this is helpful!

**Comment by reticulan** [comment]
@kturney thank you! sorry for my newbie questions

**Comment by kturney** [comment]
No problem! Glad I could help.
