### ISSUE TITLE
Export mapbox-gl module

### ISSUE THREAD

**Issue by AndreJoaquim** [kturney/ember-mapbox-gl#71]
When you use this add-on with the `lazyLoad` option to true, the `_loader` private property from the `mapbox-gl` component could set a `mapbox-gl` property containing the library that was loaded.

This way, the consuming app didn't have to import the `mapbox-gl` again, rather using the exposed variable containing the module.

**Comment by kturney** [comment]
The `mapbox-gl` component [exposes the `_map` property](https://github.com/kturney/ember-mapbox-gl/blob/e10e296b7cb10136a9641694cb01cb36caae7c5e/addon/components/mapbox-gl.js#L60). Is that enough for your purposes?

[ember-auto-import](https://github.com/ef4/ember-auto-import) (which ember-mapbox-gl uses) should support an app either dynamically or statically importing mapbox-gl-js and using the same instance of the library.

**Comment by AndreJoaquim** [comment]
The `_map` property is not enough for my purposes, because it only exports the `map` instance. I wanted the `mapbox-gl` dynamically imported "instance", i.e. [`_loader.Mapbox`](https://github.com/kturney/ember-mapbox-gl/blob/e10e296b7cb10136a9641694cb01cb36caae7c5e/addon/components/mapbox-gl.js#L61)

ember-auto-import allows the dynamic import, that you use on this add-on. However, in my consuming application, I don't want to import the `mapbox-gl` library again given the fact that it has already been dynamically imported by this add-on.

Does ember-auto-import automatically detect that a library has already been dynamically imported? If so, why do you need the [`isLoaded` flag on the loader](https://github.com/kturney/ember-mapbox-gl/blob/e10e296b7cb10136a9641694cb01cb36caae7c5e/addon/-private/mapbox-loader-dynamic.js#L9)?

**Comment by AndreJoaquim** [comment]
@kturney It seems that `ember-auto-import` automatically imports the same instance of the library. I'm closing this issue. Thanks for the help!
