### ISSUE TITLE
Could not find module `ember-mapbox-gl/-private/mapbox-loader`

### ISSUE THREAD

**Issue by maprules1000** [kturney/ember-mapbox-gl#81]
I upgraded the version of ember-cli in our app from `~3.7.1` to `~3.13.1` and I'm consistently getting this error in tests:

`Error: Could not find module 'ember-mapbox-gl/-private/mapbox-loader' imported from 'ember-mapbox-gl/components/mapbox-gl'`

I dug into it as much as I could with my slight broccoli knowledge and it seems like this [lazy loading PR](https://github.com/kturney/ember-mapbox-gl/commit/a8ce42471290439c74dcd3fcb1fca7ad209f42f0#diff-168726dbe96b3ce427e7fedce31bb0bcR15) introduced the smart importing of the `mapbox-loader` file. It seems like that file isn't correctly being added to the broccoli tree using the new Ember CLI.

Edit: can confirm that it work in `v0.12.0` and is broken in `v0.13.0` and up.

**Comment by kturney** [comment]
Sorry about that, and thanks for the issue!
The loader code always did feel a bit hacky :-).
I’ve been contemplating just having ember-mapbox-gl always dynamically load mapbox-gl, so maybe it’s time for me to just do it.

**Comment by maprules1000** [comment]
Coolio, I can open up a PR for that if it's as simple as removing the static loader and the broccoli tree code. 

~Just curious, what was the motivation behind having a static and dynamic loader?~

Ah, I think I see now. It looks like fastboot compatibility was the motivator, which is also a necessity for us.

I'm going to take a whack at some stuff today and I'll open up a PR if I find anything good.

**Comment by kturney** [comment]
The original behavior was static loading, and I wanted to add dynamic loading without making a breaking change.

**Comment by kturney** [comment]
Aiming to fix with https://github.com/kturney/ember-mapbox-gl/pull/82.

After that is merged, I'm going to do a follow on PR updating versions of things, and then I'll publish a new version.

**Comment by kturney** [comment]
published in `0.16.0`

**Comment by kturney** [comment]
hi @maprules1000, have you had a chance to check that `0.16.0` fixes your issue?

**Comment by allthesignals** [comment]
Upgrading some stuff and seeing this:

```bash
TypeError: /Users/mattgardner/labs-zola/ember-in-element-polyfill/helpers/-clear-element.js: (0 , _helperModuleTransforms.getModuleName) is not a function
```

Going to try 1.0+ versions...

Full dump:
[error.dump.ac88d2a5a5d4a8efc816304fb8ac4c88.log](https://github.com/kturney/ember-mapbox-gl/files/9023754/error.dump.ac88d2a5a5d4a8efc816304fb8ac4c88.log)
