### ISSUE TITLE
Documentation in gh-pages broken?

### ISSUE THREAD

**Issue by vasilakisfil** [kturney/ember-mapbox-gl#84]
Thanks for this awesome addon!

Anything past Installation link doesn't seem to work, for instance [The Container](https://kturney.github.io/ember-mapbox-gl/versions/v0.16.0/docs/container) is the same as Installation.

Is that expected ?

**Comment by kturney** [comment]
hi @vasilakisfil.
The link in your issue loaded to the correct spot for me.
<img width="1430" alt="Screen Shot 2019-10-16 at 1 45 42 PM" src="https://user-images.githubusercontent.com/675967/66949010-5efe0600-f01b-11e9-93f9-8d3f70644534.png">

What error are you seeing?

**Comment by vasilakisfil** [comment]
@kturney the problem (I think it's a problem?) is that all links on the side load the same page (the installation one), the one that says in the top `Note: The example below uses ember-composable-helpers`. All except Introduction and Installation.

**Comment by vasilakisfil** [comment]
hmm from what I see, all pages load the docs from here: https://github.com/kturney/ember-mapbox-gl/tree/master/tests/dummy/app/templates/docs where basically docs for other pages are the same as Installation. So I think the issue is that docs are missing, right ?

**Comment by kturney** [comment]
ah. I see now. The title on the page changes, but the content is the same.
very strange!
I'll take a look.
Thanks for reporting!

**Comment by kturney** [comment]
hi @vasilakisfil,

I've fixed the immediate issue [on master](https://github.com/kturney/ember-mapbox-gl/commit/f516907befdbfe53ddc888146d5f72f725e8f753).
Thanks again for submitting the issue!

corrected docs here: https://kturney.github.io/ember-mapbox-gl/versions/master/docs/
