### ISSUE TITLE
Error on Building App with `ember-mapbox-gl`

### ISSUE THREAD

**Issue by kushthedude** [kturney/ember-mapbox-gl#85]
I just migrated my app from `ember-g-map` to `ember-mapbox-gl` whenever I fire up my application, it runs into this error : 
```sh
Build Error (broccoli-persistent-filter:Babel > [Babel: ember-mapbox-gl]) in ember-mapbox-gl/-private/mapbox-loader.js

Cannot read property 'getHash' of null


Stack Trace and Error Report: /var/folders/05/32b0q3c134b032psxm8569f80000gn/T/error.dump.1b86d868572b84d644fcddbf9b9cb36b.log
```

**Comment by kushthedude** [comment]
Our app is on Ember-CLI 3.10 with fast boot enabled. @kturney Any solution or reason why such behaviour is present.

**Comment by kturney** [comment]
Hi @kushthedude,

I personally haven’t used fastboot, but I think that error is caused by mapboxgl accessing something browser specific.

I think the easiest solution will be to only render the mapbox-gl when in the browser via an if in the template.

**Comment by kushthedude** [comment]
> I personally haven’t used fastboot, but I think that error is caused by mapboxgl accessing something browser specific.

Hey @kturney , Thanks for your quick reply.

I got to know something I was booting on development environment in which Fastboot is disabled, Also not to mention I am rendering the example template only. I am still getting this error. Is it to do anything with the version of `Brocolli-persistent-filter`, I am at 2.0 ?

**Comment by kushthedude** [comment]
Upgrading the filter isn't any good .

**Comment by kturney** [comment]
can you post the content of the error log mentioned?
`/var/folders/05/32b0q3c134b032psxm8569f80000gn/T/error.dump.1b86d868572b84d644fcddbf9b9cb36b.log`
