### ISSUE TITLE
map sometimes fails to load

### ISSUE THREAD

**Issue by gabrielgrant** [kturney/ember-mapbox-gl#89]
Thanks a ton for this addon -- overall makes it waaay nicer than having to deal with all the lifecycle stuff manually -- but finding that I'm sometimes getting a blank map rendered:

![image](https://user-images.githubusercontent.com/493968/83798500-32a20300-a659-11ea-9d75-c5e1083ee0ff.png)

For context, here's what it looks like when it works: 

![image](https://user-images.githubusercontent.com/493968/83798404-14d49e00-a659-11ea-8663-3cdd17276229.png)

I added a mapLoaded event handler which gets triggered fine when the map loads correctly, but when it's showing up blank, the action isn't getting triggered (which i presume is also causing the mapbox-gl component to not yield, and so no subcomponents are rendered). From looking at the requests (and considering the fact that the background is colored), it does seem like the custom style is getting loaded properly.

Having trouble figuring out where the breakdown is happening. Any ideas what could be causing this, or more info i could provide to try to debug?

In case it is relevant, the custom style is set in the global config, the markers are rendered using individual `map.marker` components

**Comment by kturney** [comment]
Hi @gabrielgrant, that sounds like a tricky one!
If an error occurs during loading, the map component [yields the error that occurred](https://github.com/kturney/ember-mapbox-gl/blob/05f918499e17d811ca2154e0e7fc8c3f7f3aed15/addon/templates/components/mapbox-gl.hbs#L17), so the first thing I would check is if there is any useful information in the error.
The error should also [have an `event` property on it containing the original mapbox error](https://github.com/kturney/ember-mapbox-gl/blob/05f918499e17d811ca2154e0e7fc8c3f7f3aed15/addon/-private/mapbox-loader.js#L13).

**Comment by gabrielgrant** [comment]
Ah, thanks for the reply, @kturney -- hadn't noticed that I could get the error with the inverse block. But I don't believe there was any error being thrown (/auto-logged), AFAICT it was just hanging before the onLoad event fires

Did find a [few](https://github.com/mapbox/mapbox-gl-js/issues/6707) [mapbox](https://github.com/mapbox/mapbox-gl-js/issues/6708) [issues](https://github.com/mapbox/mapbox-gl-js/issues/2268#issuecomment-401979967) related to strangeness with onLoad, so possible it is related to one of those?

Noticed that I wasn't able to repro in an incognito window, so cleared my cache, which seems to have fixed it for the time being (mostly -- it re-occurred once, but after clearing the cache again it has yet to come back). Not a _super_ satisfying answer, but better than not working at all :P 

Not sure if you want to leave this open in hopes of tracking down the root cause, but now that i at least have a workaround (and am no longer able to repro), would certainly be fine with closing until I have more useful info

**Comment by kturney** [comment]
I'll go ahead and close because it sounds like some form of caching issue within mapbox itself.
If you do manage to track down some error case that we missed exposing, please let me know!
