### ISSUE TITLE
mapbox-gl-layer should support 'before' parameter for layer ordering

### ISSUE THREAD

**Issue by allthesignals** [kturney/ember-mapbox-gl#9]
MapboxGL's [`addLayer`](https://www.mapbox.com/mapbox-gl-js/api/#map#addlayer) function accepts two arguments, an options hash and a `before` string. `before` indicates the order in which a layer is rendered. If left blank, it adds it to the end of the layers array. 

Proposed solution is to add a parameter for the component `before` and pass it if it's defined. Spread syntax would work here to avoid and ugliness in the code.

**Comment by chriswhong** [comment]
+1, we chose to migrate to mapboxGL on [this ember project](https://github.com/nycplanning/labs-community-portal/) specifically so we could take advantage of putting data layers underneath labels.
