### ISSUE TITLE
How to handle MapboxLoaderCancelledError

### ISSUE THREAD

**Issue by beerlington** [kturney/ember-mapbox-gl#95]
We're seeing some exceptions in our application related to this error and it's not clear why this exception is thrown or how it's intended to be used. Is this an exception we should be concerned with or is it just being used for flow control?

We're hitting both of these occasionally:

https://github.com/kturney/ember-mapbox-gl/blob/e2408d4c8c37136b524912e02494e7c0ad55e7a1/addon/-private/mapbox-loader.js#L57-L59

https://github.com/kturney/ember-mapbox-gl/blob/e2408d4c8c37136b524912e02494e7c0ad55e7a1/addon/-private/mapbox-loader.js#L93-L95

**Comment by kturney** [comment]
Hi Peter,

You are correct. That error is just used for flow control. It will be thrown if a map component is created and then destroyed before loading completes.

I would have expected https://github.com/kturney/ember-mapbox-gl/blob/e2408d4c8c37136b524912e02494e7c0ad55e7a1/addon/-private/mapbox-loader.js#L117 to detect the thrown exception though, so it does seem like a bug that it is still getting logged.

**Comment by kturney** [comment]
Hi Peter,

To try to reproduce the situation that you are encountering I added this test locally
```js
test('clean log on cancel', async function (assert) {
  assert.expect(0);

  await render(hbs`
    {{#mapbox-gl as |map|}}
      <div id='loaded-sigil'></div>
    {{/mapbox-gl}}
  `);

  await clearRender();
});
```

After adding some logs, I can see that this test does cancel the map load before it is complete, causing a `MapboxLoaderCancelledError` to be thrown. However, the error appears to be properly detected and no console.error is logged. Are there anymore details you can provide? For instance, is the error only reported from certain browsers?

**Comment by beerlington** [comment]
@kturney I'm seeing it on a variety of browsers, but the most common seem to be desktop Safari on Mac (11.1, 12.1, 14.0), mobile Safari on iOS (13, 14), and whatever browser Instagram uses on iOS. I don't see desktop Chrome or Firefox in any of the error reports we've received.

**Comment by kturney** [comment]
I was also unable to reproduce this in desktop Safari 14.0.
Would you be able to provide a test case or reproduction?
Or maybe one of the stack traces from an error report?
